# Generated by Django 3.2.3 on 2021-05-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleated_at', models.DateTimeField(auto_now_add=True, verbose_name='登録時間')),
                ('temperture', models.FloatField(blank=True, verbose_name='気温')),
                ('humidity', models.FloatField(blank=True, verbose_name='湿度')),
            ],
            options={
                'verbose_name': '採取データ',
                'verbose_name_plural': '採取データ',
            },
        ),
    ]
