# Generated by Django 3.2.3 on 2021-05-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cleated_at_log_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='temperture',
            new_name='temperature',
        ),
    ]
